---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: zta-demo
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: zta-demo
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: zta-demo
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: zta-demo
automountServiceAccountToken: false
